Author.destroy_all
Book.destroy_all

Author.create(:name => 'Stephen King', :bio => 'Is an American author of contemporary horror, suspense, science fiction and fantasy. His books have sold more than 350 million copies[9] and have been adapted into a number of feature films, television movies and comic books. King has published 50 novels, including seven under the pen-name of Richard Bachman, and five non-fiction books. He has written nearly two hundred short stories, most of which have been collected in nine collections of short fiction. Many of his stories are set in his home state of Maine. ', :genre => 'Thriller', :image => 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTqgNzYb09XznaG9u3mbI-4xaU-NXg8U1Zf9xWrxQlWkbjFukSu8g.jpg')

Author.create(:name => 'Jim Morrison', :bio => 'James Douglas Jim Morrison (December 8, 1943 – July 3, 1971) was an American singer-songwriter and poet, best remembered as the lead singer of Los Angeles rock band The Doors.[1] From a young age, Morrison developed an alcohol dependency which led to his death at the age of 27 in Paris. He is alleged to have died of a heroin overdose, but as no autopsy was performed, the exact cause of his death is still disputed. Morrison was well known for often improvising spoken word poetry passages while the band played live. Due to his wild personality and performances, he is regarded by critics and fans as one of the most iconic, charismatic, and pioneering frontmen in rock music history.[3] Morrison was ranked number 47 on Rolling Stones list of the 100 Greatest Singers of All Time, and number 22 on Classic Rock Magazines 50 Greatest Singers In Rock. Morrison was known as the self-proclaimed King of Orgasmic Rock.', :genre => 'Poetry', :image => 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Jim_Morrison_1969.JPG/503px-Jim_Morrison_1969.jpg')

Author.create(:name => 'Carl Jung', :bio => 'was a Swiss psychotherapist and psychiatrist who founded analytical psychology. Jung proposed and developed the concepts of the extraverted and the introverted personality, archetypes, and the collective unconscious. His work has been influential in psychiatry and in the study of religion, literature, and related fields.', :genre => 'Psychology', :image => 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Jung_1910-crop.jpg/315px-Jung_1910-crop.jpg')


Book.create(:title => 'The Green Mile', :description=> 'The Green Mile is a 1996 serial novel written by Stephen King. It tells the story of death row supervisor Paul Edgecombes encounter with John Coffey, an unusual inmate who displays inexplicable healing and empathetic abilities. the serial novel was originally released in six volumes before being republished as a single volume work. the book is an example of magical realism.', :isbn => '9780684853529', :image => 'http://upload.wikimedia.org/wikipedia/en/f/f7/greenmilepart1.jpg')

Book.create(:title => 'on writing', :description=> 'is a memoir of the authors experiences as a writer, and also serves as a guide book for those who choose to enter the craft. In 2008, Entertainment Weekly listed On Writing 21st on their list of The New Classics: Books – The 100 best reads from 1983 to 2008, making it Kings only entry.', :isbn => '9780684853529', :image => 'http://upload.wikimedia.org/wikipedia/en/6/62/onwriting.jpg')

Book.create(:title => 'The American Night', :description=> 'Intense, erotic, and enigmatic, Jim Morrisons persona is as riveting now as the lead singer/composer Lizard King was during The Doors peak in the late sixties. His fast life and mysterious death remain controversial more than twenty years later. The Lords and the New Creatures, Morrisons first published volume of poetry, is an uninhibited exploration of societys dark side -- drugs, sex, fame, and death -- captured in sensual, seething images. Here, Morrison gives a revealing glimpse at an era and at the man whose songs and savage performances have left their indelible impression on our culture.', :isbn => '0671210440', :image => 'http://d.gr-assets.com/books/1348223967l/535734.jpg')

Book.create(:title => 'Synchronicity: An Acausal Connecting Principle. (From Vol. 8. of the Collected Works of C. G. Jung) ', :description=> 'Jung was intrigued from early in his career with coincidences, especially those surprising juxtapositions that scientific rationality could not adequately explain. He discussed these ideas with Albert Einstein before World War I, but first used the term synchronicity in a 1930 lecture, in reference to the unusual psychological insights generated from consulting the I Ching. A long correspondence and friendship with the Nobel Prize-winning physicist Wolfgang Pauli stimulated a final, mature statement of Jungs thinking on synchronicity, originally published in 1952 and reproduced here. Together with a wealth of historical and contemporary material, this essay describes an astrological experiment Jung conducted to test his theory. Synchronicity reveals the full extent of Jungs research into a wide range of psychic phenomena.', :isbn => '0691150508', :image => 'http://symbolwatcher.com/wp-content/uploads/2009/08/synchronicity-an-acausal-connecting-principle-by-cg-jung.jpg')






